const STRUCTURE_DIRS = [
  ".obsidian",
  "bin",
  "commands",
  "src",
  "config",
  "config/prompts",
  "config/policies",
  "config/schemas",
  "inbox",
  "inbox/drop_here",
  "inbox/self",
  "raw",
  "raw/pdfs",
  "raw/web",
  "raw/images",
  "raw/repos",
  "raw/datasets",
  "raw/notes",
  "raw/transcripts",
  "manifests",
  "extracted",
  "extracted/text",
  "extracted/images",
  "extracted/metadata",
  "extracted/figures",
  "extracted/tables",
  "wiki",
  "wiki/_maps",
  "wiki/_indices",
  "wiki/_templates",
  "wiki/source-notes",
  "wiki/concepts",
  "wiki/entities",
  "wiki/companies",
  "wiki/macro",
  "wiki/market-structure",
  "wiki/derivatives",
  "wiki/timelines",
  "wiki/theses",
  "wiki/surveillance",
  "wiki/watch-profiles",
  "wiki/questions",
  "wiki/synthesis",
  "wiki/glossary",
  "wiki/unresolved",
  "wiki/self",
  "wiki/self/inbox",
  "wiki/self/principles",
  "wiki/self/heuristics",
  "wiki/self/anti-patterns",
  "wiki/self/decision-rules",
  "wiki/self/portfolio-philosophy",
  "wiki/self/postmortems",
  "wiki/self/bias-watch",
  "wiki/self/communication-style",
  "outputs",
  "outputs/reports",
  "outputs/decks",
  "outputs/charts",
  "outputs/briefs",
  "outputs/memos",
  "outputs/screens",
  "logs",
  "logs/actions",
  "logs/agent_runs",
  "logs/lint",
  "logs/report_runs",
  "cache",
  "tests",
  "tests/fixtures"
];

const SOURCE_TYPE_BY_EXTENSION = {
  ".pdf": "paper",
  ".md": "article",
  ".markdown": "article",
  ".html": "web",
  ".htm": "web",
  ".txt": "note",
  ".rtf": "note",
  ".csv": "dataset",
  ".tsv": "dataset",
  ".json": "dataset",
  ".jsonl": "dataset",
  ".xlsx": "dataset",
  ".xls": "dataset",
  ".parquet": "dataset",
  ".png": "image",
  ".jpg": "image",
  ".jpeg": "image",
  ".webp": "image",
  ".gif": "image",
  ".svg": "image",
  ".bmp": "image",
  ".zip": "repo",
  ".tar": "repo",
  ".gz": "repo",
  ".tgz": "repo"
};

const RAW_SUBDIR_BY_SOURCE_TYPE = {
  paper: "pdfs",
  article: "web",
  web: "web",
  image: "images",
  repo: "repos",
  dataset: "datasets",
  note: "notes",
  transcript: "transcripts"
};

const TEXT_EXTENSIONS = new Set([
  ".md",
  ".markdown",
  ".txt",
  ".csv",
  ".tsv",
  ".json",
  ".jsonl",
  ".html",
  ".htm",
  ".rtf",
  ".xml",
  ".yaml",
  ".yml"
]);

const HTML_EXTENSIONS = new Set([".html", ".htm"]);
const IMAGE_EXTENSIONS = new Set([".png", ".jpg", ".jpeg", ".webp", ".gif", ".svg", ".bmp"]);

const REQUIRED_FRONTMATTER = {
  "source-note": [
    "id",
    "kind",
    "title",
    "source_type",
    "ingested_at",
    "raw_path",
    "metadata_path",
    "status"
  ],
  "concept-page": ["id", "kind", "title", "status"],
  "entity-page": ["id", "kind", "title", "entity_type", "status"],
  "thesis-page": ["id", "kind", "title", "status"],
  "watch-profile": ["id", "kind", "title", "status", "priority", "cadence"],
  "question-page": ["id", "kind", "title", "status", "confidence"],
  "surveillance-page": ["id", "kind", "title", "status"],
  "principle-note": ["id", "kind", "title", "status", "confidence"],
  "heuristic-note": ["id", "kind", "title", "status", "confidence"],
  "bias-watch-note": ["id", "kind", "title", "status", "confidence"],
  "anti-pattern-note": ["id", "kind", "title", "status", "confidence"],
  "decision-rule-note": ["id", "kind", "title", "status", "confidence"],
  "portfolio-philosophy-note": ["id", "kind", "title", "status", "confidence"],
  "postmortem-note": ["id", "kind", "title", "status", "confidence"],
  "communication-style-note": ["id", "kind", "title", "status", "confidence"]
};

const STOPWORDS = new Set([
  "a",
  "about",
  "after",
  "against",
  "all",
  "also",
  "an",
  "and",
  "are",
  "as",
  "at",
  "be",
  "because",
  "been",
  "before",
  "between",
  "both",
  "but",
  "by",
  "can",
  "could",
  "did",
  "do",
  "does",
  "for",
  "from",
  "had",
  "has",
  "have",
  "how",
  "if",
  "into",
  "is",
  "it",
  "its",
  "just",
  "more",
  "most",
  "not",
  "of",
  "on",
  "or",
  "out",
  "over",
  "recent",
  "same",
  "should",
  "so",
  "some",
  "such",
  "than",
  "that",
  "the",
  "their",
  "them",
  "then",
  "there",
  "these",
  "they",
  "this",
  "those",
  "through",
  "to",
  "too",
  "under",
  "use",
  "using",
  "very",
  "was",
  "were",
  "what",
  "when",
  "where",
  "which",
  "while",
  "who",
  "why",
  "with",
  "you",
  "your"
]);

module.exports = {
  HTML_EXTENSIONS,
  IMAGE_EXTENSIONS,
  RAW_SUBDIR_BY_SOURCE_TYPE,
  REQUIRED_FRONTMATTER,
  SOURCE_TYPE_BY_EXTENSION,
  STOPWORDS,
  STRUCTURE_DIRS,
  TEXT_EXTENSIONS
};
